<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="ackermann_bot">

  <!-- Robot Properties -->
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_width" value="0.05"/>
  <xacro:property name="wheel_base" value="1.0"/>
  <xacro:property name="track_width" value="0.5"/>
  <xacro:property name="chassis_length" value="1.2"/>
  <xacro:property name="chassis_width" value="0.6"/>
  <xacro:property name="chassis_height" value="0.2"/>

  <!-- Plugins -->
  <xacro:include filename="$(find xacro)/gazebo/gazebo.xacro"/>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="20.0"/>
      <inertia ixx="1" iyy="1" izz="1" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- Wheel Macro -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}_wheel">
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.0"/>
        <inertia ixx="0.01" iyy="0.01" izz="0.01"/>
      </inertial>
    </link>

    <joint name="${name}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}_wheel"/>
      <origin xyz="${x} ${y} ${-wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Front Left Steering Wheel -->
  <xacro:wheel name="front_left" x="${wheel_base/2}" y="${track_width/2}"/>
  <!-- Front Right Steering Wheel -->
  <xacro:wheel name="front_right" x="${wheel_base/2}" y="${-track_width/2}"/>
  <!-- Rear Left Drive Wheel -->
  <xacro:wheel name="rear_left" x="${-wheel_base/2}" y="${track_width/2}"/>
  <!-- Rear Right Drive Wheel -->
  <xacro:wheel name="rear_right" x="${-wheel_base/2}" y="${-track_width/2}"/>

  <!-- Steering Joints -->
  <joint name="front_left_steering_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_left_wheel"/>
    <origin xyz="${wheel_base/2} ${track_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.5" upper="0.5" effort="10" velocity="1"/>
  </joint>

  <joint name="front_right_steering_joint" type="revolute">
    <parent link="base_link"/>
    <child link="front_right_wheel"/>
    <origin xyz="${wheel_base/2} ${-track_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.5" upper="0.5" effort="10" velocity="1"/>
  </joint>

  <!-- ros2_control -->
  <ros2_control name="AckermannBotControl" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="rear_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="front_left_steering_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
    </joint>
    <joint name="front_right_steering_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
    </joint>
  </ros2_control>

</robot>
